apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: ubuntu

resources:
  - deployment.yml
  # - service.yml

configMapGenerator:
  - name: public-key-config
    namespace: cg-akeyless
    files:
      - ca.pub
  - name: startup-script-config
    namespace: cg-akeyless
    files:
    - startup.sh