apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  namespace: cg-akeyless
  labels:
    app: ubuntu
  annotations:
    {}
spec:
  type: LoadBalancer
  ports:
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app: ubuntu